FROM code4hep-build:latest

COPY --from=localhost/code4hep-build-final /opt/spack /opt/spack

RUN apt-get update && apt-get install -y \
    python3 \
    bash \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

SHELL ["/bin/bash", "-c"]

RUN echo "source /opt/spack/share/spack/setup-env.sh" >> /root/.bashrc && \
    echo "spack env activate code4hep_env" >> /root/.bashrc && \
    echo "source \$(spack location -i stitched)/bin/stitched_env.sh" >> /ro>

CMD ["bash"]