name: Build Code4hep

on:
  push:
  pull_request:

jobs:
#  pre-commit:
#    name: Code format & static checks
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-python@v5
#        with:
#          python-version: "3.12"
#      - uses: pre-commit/action@v3.0.1

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/virajnain/code4hep-ci:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and test Code4hep
        run: |
          source /opt/spack/share/spack/setup-env.sh
          spack env activate code4hep_env
          cd /scratch/build
          ./setup.sh
          cd Code4hep/build   # confirm this matches your actual build dir
          ctest --output-on-failure
#  static-analysis:
#    name: Static Analysis
#    runs-on: ubuntu-latest
#    container:
#      image: ghcr.io/virajnain/code4hep-ci:latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Build Code4hep and run static analysis
#        run: |
#          source /opt/spack/share/spack/setup-env.sh
#          spack env activate code4hep_env
#          cd /scratch/build
#          ./setup.sh
#          find /scratch/build -name 'compile_commands.json'
#          run-clang-tidy -p /scratch/build/<path-to-build-dir>
